name: Automate Preprocessing Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn

      - name: Run automate preprocessing
        run: |
          cd preprocessing
          python automate_NaylaFaizaGusvieA.py ../diabetes_prediction_dataset.csv

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-preprocessed
          path: preprocessing/diabetes_preprocessing/
